### PR TITLE
webd first task

### PR DESCRIPTION
**Pull request by SubhamPanda2003**
Issue: 1

### CODE REVIEW

**Comment by Mudit018** [comment]
@Shubhankit-Pandey 
Repo link was needed in the JSON file and not the website link

**Comment by Shubhankit-Pandey** [comment]
Sir I have given the repo link only  "
https://github.com/Shubhankit-Pandey/my-first-repo.git".

**Comment by daniel-aracquine** [comment]
paste this repo link in the json file.. you have provided the live website link there @Shubhankit-Pandey

**Comment by Mudit018** [comment]
@SubhamPanda2003 
Provide the github repo link in JSON file, you have provided the website's link

**Comment by SubhamPanda2003** [comment]
Pls check, I have changed the file.

**Comment by Mudit018** [comment]
@SubhamPanda2003 
Make another PR for task2

**Pull request merged**
