### PR TITLE
task 2

### PR DESCRIPTION
**Pull request by Aneesh7777**
Issue: 194

### CODE REVIEW

**Review by daniel-aracquine — CHANGES_REQUESTED** [review]
Provide live link to the website.
@Aneesh7777

**Comment by Aneesh7777** [comment]
http://127.0.0.1:5500/new.html
hello sir ...here is the link for website fro task 2

**Comment by Aneesh7777** [comment]
in which format do I have to add in website rep

**Comment by Mudit018** [comment]
This link is incorrect. You had to host the website on any of the discussed platforms

**Pull request closed without merging**
