### PR TITLE
Task-2 Completed

### PR DESCRIPTION
**Pull request by AasthaaPal**
Issue: 194
https://aasthaapal.github.io/Web-D-Task-2/

### CODE REVIEW

**Comment by Mudit018** [comment]
@AasthaaPal 
Issue no. is wrong in PR.

**Comment by AasthaaPal** [comment]
sir the issue no is 2 only..right? What change should I make in it?

**Comment by Mudit018** [comment]
@AasthaaPal 
Issue no. is 194

**Comment by AasthaaPal** [comment]
ok sir

**Pull request merged**
