### PR TITLE
task 1 by vishnu

### PR DESCRIPTION
**Pull request by kvishnuprasanth**
Issue: 1

### CODE REVIEW

**Comment by Mudit018** [comment]
@kvishnuprasanth 
Message field is incorrect at the last
it is not an **input** field

**Comment by kvishnuprasanth** [comment]
> @kvishnuprasanth 
> Message field is incorrect at the last
> it is not an **input** field
 I'll check it sir thank you

**Comment by kvishnuprasanth** [comment]
Sir I've committed some changes in my repo, if it's possible please recheck
it.
GitHub Id : kvishnuprasanth

**Comment by Mudit018** [comment]
image

This part needs to be changed
and for second task you have to make separate PR, first correct first and make first PR and then you can make the second one

**Comment by kvishnuprasanth** [comment]
Message field changed to textarea sir.

**Comment by Mudit018** [comment]
@kvishnuprasanth 
Make separate PR for task 2 else you won't get marks for the second one

**Comment by kvishnuprasanth** [comment]
I am facing some confusion here sir

**Pull request merged**
