### PR TITLE
Task3

### PR DESCRIPTION
**Pull request by Himanshu276330**
Issue: 292
https://himanshu276330.github.io/WebD-Workshop-Task3/

### CODE REVIEW

**Comment by Himanshu276330** [comment]
Live website -> https://himanshu276330.github.io/WebD-Workshop-Task3/

**Review by Mudit018 — CHANGES_REQUESTED** [review]
Provide the live website link

**Comment by Himanshu276330** [comment]
Live website -> https://himanshu276330.github.io/WebD-Workshop-Task3/

**Comment by Himanshu276330** [comment]
@Mudit018  sir i give live website link in comment, and i also add it in PR

**Comment by Himanshu276330** [comment]
https://himanshu276330.github.io/WebD-Workshop-Task3/index.html

**Review by aknsal — APPROVED** [review]

**Comment by Himanshu276330** [comment]
Thanks Sir

**Pull request merged**
