### PR TITLE
WebD Task 2 completed by atharva-gadekar

### PR DESCRIPTION
**Pull request by atharva-gadekar**
Issue: 194

https://atharva-gadekar.github.io/WebD-Task2-APK-22/atharva-gadekar.html

### CODE REVIEW

**Review by Mudit018 — CHANGES_REQUESTED** [review]
Issue no. is 194 and provide the live website link

**Comment by atharva-gadekar** [comment]
> Issue no. is 194 and provide the live website link

I have changed the Issue, please check now

**Comment by Mudit018** [comment]
> > Issue no. is 194 and provide the live website link
> 
> I have changed the Issue, please check now

Message field is not input, replace it with textarea

**Comment by atharva-gadekar** [comment]
> > > Issue no. is 194 and provide the live website link
> > 
> > 
> > I have changed the Issue, please check now
> 
> Message field is not input, replace it with textarea
> Made the necessary changes. Please check now.

**Pull request merged**
