### PR TITLE
tsunami03 completed task-2

### PR DESCRIPTION
**Pull request by tsunami03**
Issue: 194

### CODE REVIEW

**Comment by tsunami03** [comment]
https://tsunami03.github.io/WebD-Tasks-APK22/tsunami03

**Comment by tsunami03** [comment]
https://tsunami03.github.io/WebdTask2/tsunami03

**Comment by tsunami03** [comment]
Issue: 2

**Comment by Mudit018** [comment]
@tsunami03 
Issue no. is wrong in PR.

**Comment by tsunami03** [comment]
@Mudit018 I have edited the comment.

**Pull request merged**
