### PR TITLE
Task2 done

### PR DESCRIPTION
**Pull request by antsharma**
Issue: 194
https://github.com/antsharma/WebD-task-2.git

### CODE REVIEW

**Review by Mudit018 — CHANGES_REQUESTED** [review]
The website you hosted with the given link is not what we had given in the task

**Comment by antsharma** [comment]
https://antsharma.github.io/WebD-task-2/
I have changed the repo and attached the correct HTML website in readme. Please merge this PR

**Comment by antsharma** [comment]
Sorry for the inconvenience.
I have now attached the correct HTML website in ReadMe .
Please merge this PR

**Comment by Mudit018** [comment]
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0cm;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:612.0pt 792.0pt;
	margin:72.0pt 72.0pt 72.0pt 72.0pt;}
div.WordSection1
	{page:WordSection1;}

**Pull request merged**
