### PR TITLE
task-2-done

### PR DESCRIPTION
**Pull request by Sakshi-Khokhar**
Issue: 194

### CODE REVIEW

**Review by aknsal — CHANGES_REQUESTED** [review]
Use textarea for message input.

**Comment by Sakshi-Khokhar** [comment]
What kind of changes sir

**Comment by aknsal** [comment]
In the message input you have used `<input>` tag with type `text`, instead of that you have to use `<textarea>` tag

**Comment by Sakshi-Khokhar** [comment]
So sir do I have to make the changes in the code and then again give u the
pull request?

**Comment by aknsal** [comment]
Just do the changes commit it and tell me.

**Comment by Sakshi-Khokhar** [comment]
Sir i have committed changes
Plss check if everything is alright or not

**Comment by Mudit018** [comment]
image
This part is incorrect.
You have used input field type rather it is text area, so use text area

**Comment by Sakshi-Khokhar** [comment]
Sir i have changed input to text area
Plss see

**Review by Mudit018 — CHANGES_REQUESTED** [review]
image
Still it is input only

**Comment by Sakshi-Khokhar** [comment]
Done Sir... I Have Updated My html code!

**Pull request merged**
