### PR TITLE
Task2

### PR DESCRIPTION
**Pull request by poga0204**
Issue: 194
https://poga0204.github.io/WEBD-task2/

### CODE REVIEW

**Review by Mudit018 — CHANGES_REQUESTED** [review]
Issue no. is 194

**Comment by poga0204** [comment]
Made the changes

**Review by Mudit018 — CHANGES_REQUESTED** [review]
Issue no. is 194

**Comment by Mudit018** [comment]
image
This issue no. needs to be changed

**Comment by poga0204** [comment]
Please check now

**Pull request merged**
