### PR TITLE
webd_task2

### PR DESCRIPTION
**Pull request by CodeWithGauravSingh**
Issue: 194

### CODE REVIEW

**Review by Mudit018 — CHANGES_REQUESTED** [review]
Provide live website link

**Comment by CodeWithGauravSingh** [comment]
live website link :-   https://codewithgauravsingh.github.io/Webd_Task2/task2.html

**Review by Mudit018 — CHANGES_REQUESTED** [review]
Message box is not an input field type. Use textbox!!!

**Comment by CodeWithGauravSingh** [comment]
sir i changed input to text area

**Pull request merged**
